const vacancies = [
    {
        vacancy_id: 1,
        vacancy_name: "Js Test1",
        vacancy_description: "hello test1 descr",
        creation_data: "01.01.2023",
        vacancy_category: "JavaScript",
        form_of_employment: "Office",
        vacancy_country: "Ukraine",
        vacancy_city: "Kyiv",
        expected_candidate_location: "Ukraine",
        salary_from: 1000,
        salary_to: 1300,
        expected_work_experience: 2,
        expected_english_level: "Anvanced",
        vacancy_company_type: "Outsorce",
    },
    {
        vacancy_id: 2,
        vacancy_name: "JAVA Junior",
        vacancy_description: "hello test1 descr",
        creation_data: "13.10.2023",
        vacancy_category: "Java",
        form_of_employment: "Office",
        vacancy_country: "Ukraine",
        vacancy_city: "Kyiv",
        expected_candidate_location: "Ukraine",
        salary_from: 3000,
        salary_to: 3400,
        expected_work_experience: 3,
        expected_english_level: "Anvanced",
        vacancy_company_type: "Outsorce",
    },
    {
        vacancy_id: 3,
        vacancy_name: "Python dev +",
        vacancy_description: "hello test1 descr",
        creation_data: "03.09.2023",
        vacancy_category: "Python",
        form_of_employment: "Office",
        vacancy_country: "Ukraine",
        vacancy_city: "Kyiv",
        expected_candidate_location: "Ukraine",
        salary_from:900,
        salary_to: 1000,
        expected_work_experience: 1,
        expected_english_level: "Anvanced",
        vacancy_company_type: "Outsorce",
    },
]

export default vacancies;