const vacancies = [
    {
        vacancy_id: 1,
        vacancy_name: "JavaScript Junior/Trainee",
        vacancy_description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        creation_data: "01.01.2023",
        vacancy_category: "JavaScript",
        form_of_employment: "Remote",
        vacancy_country: "Poland",
        vacancy_city: "Warsaw",
        expected_candidate_location: "Poland",
        salary_from: 300,
        salary_to: 700,
        expected_work_experience: 1,
        expected_english_level: "Anvanced",
        vacancy_company_type: "Outsorce",
    },
    {
        vacancy_id: 2,
        vacancy_name: "Java Middle Developer",
        vacancy_description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        creation_data: "13.10.2023",
        vacancy_category: "Java",
        form_of_employment: "Remote",
        vacancy_country: "Germany",
        vacancy_city: "Berlin",
        expected_candidate_location: "Germany",
        salary_from: 2500,
        salary_to: 3100,
        expected_work_experience: 4,
        expected_english_level: "Anvanced",
        vacancy_company_type: "Outsorce",
    },
    {
        vacancy_id: 3,
        vacancy_name: "Python DevOps Trainee",
        vacancy_description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        creation_data: "03.09.2023",
        vacancy_category: "Python",
        form_of_employment: "Remote",
        vacancy_country: "Ukraine",
        vacancy_city: "Kyiv",
        expected_candidate_location: "Ukraine",
        salary_from:900,
        salary_to: 1000,
        expected_work_experience: 1,
        expected_english_level: "Anvanced",
        vacancy_company_type: "Outsorce",
    },
    {
        vacancy_id: 4,
        vacancy_name: "Python DevOps Trainee",
        vacancy_description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        creation_data: "03.09.2023",
        vacancy_category: "Python",
        form_of_employment: "Remote",
        vacancy_country: "Ukraine",
        vacancy_city: "Kyiv",
        expected_candidate_location: "Ukraine",
        salary_from:900,
        salary_to: 1000,
        expected_work_experience: 1,
        expected_english_level: "Anvanced",
        vacancy_company_type: "Outsorce",
    },
    {
        vacancy_id: 5,
        vacancy_name: "Python DevOps Trainee",
        vacancy_description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        creation_data: "03.09.2023",
        vacancy_category: "Python",
        form_of_employment: "Remote",
        vacancy_country: "Ukraine",
        vacancy_city: "Kyiv",
        expected_candidate_location: "Ukraine",
        salary_from:900,
        salary_to: 1000,
        expected_work_experience: 1,
        expected_english_level: "Anvanced",
        vacancy_company_type: "Outsorce",
    },
    {
        vacancy_id: 6,
        vacancy_name: "JavaScript Junior/Trainee",
        vacancy_description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        creation_data: "01.01.2023",
        vacancy_category: "JavaScript",
        form_of_employment: "Remote",
        vacancy_country: "Ukraine",
        vacancy_city: "Kyiv",
        expected_candidate_location: "Ukraine",
        salary_from: 300,
        salary_to: 700,
        expected_work_experience: 1,
        expected_english_level: "Anvanced",
        vacancy_company_type: "Outsorce",
    },
    {
        vacancy_id: 7,
        vacancy_name: "Java Middle Developer",
        vacancy_description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        creation_data: "13.10.2023",
        vacancy_category: "Java",
        form_of_employment: "Remote",
        vacancy_country: "Ukraine",
        vacancy_city: "Kyiv",
        expected_candidate_location: "Ukraine",
        salary_from: 2500,
        salary_to: 3100,
        expected_work_experience: 4,
        expected_english_level: "Anvanced",
        vacancy_company_type: "Outsorce",
    },
    {
        vacancy_id: 8,
        vacancy_name: "JavaScript Junior/Trainee",
        vacancy_description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        creation_data: "01.01.2023",
        vacancy_category: "JavaScript",
        form_of_employment: "Remote",
        vacancy_country: "Ukraine",
        vacancy_city: "Kyiv",
        expected_candidate_location: "Ukraine",
        salary_from: 300,
        salary_to: 700,
        expected_work_experience: 1,
        expected_english_level: "Anvanced",
        vacancy_company_type: "Outsorce",
    },
    {
        vacancy_id: 9,
        vacancy_name: "Java Middle Developer",
        vacancy_description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        creation_data: "13.10.2023",
        vacancy_category: "Java",
        form_of_employment: "Remote",
        vacancy_country: "Ukraine",
        vacancy_city: "Kyiv",
        expected_candidate_location: "Ukraine",
        salary_from: 2500,
        salary_to: 3100,
        expected_work_experience: 4,
        expected_english_level: "Anvanced",
        vacancy_company_type: "Outsorce",
    },
    {
        vacancy_id: 10,
        vacancy_name: "JavaScript Junior/Trainee",
        vacancy_description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        creation_data: "01.01.2023",
        vacancy_category: "JavaScript",
        form_of_employment: "Remote",
        vacancy_country: "Ukraine",
        vacancy_city: "Kyiv",
        expected_candidate_location: "Ukraine",
        salary_from: 300,
        salary_to: 700,
        expected_work_experience: 1,
        expected_english_level: "Anvanced",
        vacancy_company_type: "Outsorce",
    },
    {
        vacancy_id: 11,
        vacancy_name: "Java Middle Developer",
        vacancy_description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        creation_data: "13.10.2023",
        vacancy_category: "Java",
        form_of_employment: "Remote",
        vacancy_country: "Ukraine",
        vacancy_city: "Kyiv",
        expected_candidate_location: "Ukraine",
        salary_from: 2500,
        salary_to: 3100,
        expected_work_experience: 4,
        expected_english_level: "Anvanced",
        vacancy_company_type: "Outsorce",
    },
]

export default vacancies;